stages:
  train:
    cmd: python src/train.py
    deps:
    - data/fashion_mnist_data.pkl
    - src/train.py
    params:
    - train.batch_size
    - train.dropout
    - train.hidden_units
    - train.lr
    - train.num_epochs
    outs:
    - output/model.h5
    metrics:
    - dvclive/metrics.json:
        cache: false
    plots:
    - dvclive/plots/metrics/accuracy.tsv:
        cache: false
    - output/train_logs.csv:
        cache: false
        template: linear
        x: epoch
        y: accuracy
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/fashion_mnist_data.pkl
    - output/model.h5
    - src/evaluate.py
    metrics:
    - output/metrics.json:
        cache: false
    plots:
    - output/predictions.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
    - output/test/samples_of_mispredicted_images/:
        cache: false
artifacts:
  cnn-classifier: 
    path: s3://models/cnn-classifier.pt
    type: model
    desc: 'CNN'
    labels:
      - fashion-mnist
      - classification
      - cnn